name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build . -t my-model:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-model:latest ${{ secrets.DOCKER_HUB_USERNAME }}/my-model:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-model:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-model:latest

      - name: Run Docker container
        run: |
          docker run -d -p 80:80 --name my-model-prod ${{ secrets.DOCKER_HUB_USERNAME }}/my-model:latest
